### ISSUE TITLE
폰트가 바로 적용되지 않음

### ISSUE THREAD

**Issue by JangJua** [PURPLECODE-TEAM/developer-designer-personality-test#8]
폰트가 바로 적용되지 않아 깜박거리는 문제가 있음

**Comment by highcastlee** [comment]
styled-components는 새로운 스타일이 render 될 때마다, <style>태그를 변경 하고,
<style> 태그 안에 폰트 정의가 함께 있으면 새로운 스타일이 등장할 때마다, font를 재요청한다고 합니다.
해당 이슈 키워드는 크게보면 FOUC라고 볼 수 있는데, styled-components 상의 문제인 것 같습니다.
GlobalStyle.js가 아닌 app.css 파일 내에 해당 폰트를 정의하고, app.jsx에 import하여 해결했습니다.
styled-components issue 페이지에서도 개발자가 현재는 이런 방식으로 우선 해결하라고 이야기하고 있습니다.

참고한 블로그와 해당 github issue 주소를 첨부해드립니다.

[블로그] https://ryublock.tistory.com/37
[github] https://github.com/styled-components/styled-components/issues/1593
